/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const AnalysisDirection = IDL.Variant({
  'bullish' : IDL.Null,
  'sideways' : IDL.Null,
  'bearish' : IDL.Null,
});
export const CandlestickPattern = IDL.Variant({
  'shootingStar' : IDL.Null,
  'doji' : IDL.Null,
  'none' : IDL.Null,
  'hammer' : IDL.Null,
  'engulfing' : IDL.Null,
});
export const ResistanceLevel = IDL.Record({
  'strength' : IDL.Nat,
  'price' : IDL.Float64,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const AnalysisResult = IDL.Record({
  'direction' : AnalysisDirection,
  'trendStrength' : IDL.Nat,
  'candlestickPatterns' : IDL.Vec(CandlestickPattern),
  'breakouts' : IDL.Bool,
  'resistanceLevels' : IDL.Vec(ResistanceLevel),
  'timestamp' : IDL.Int,
  'confidencePercentage' : IDL.Nat,
  'image' : ExternalBlob,
  'pullbacks' : IDL.Bool,
});
export const Timeframe = IDL.Variant({
  'M1' : IDL.Null,
  'M5' : IDL.Null,
  'M10' : IDL.Null,
});
export const UserSettings = IDL.Record({
  'theme' : IDL.Text,
  'signalNotifications' : IDL.Bool,
  'language' : IDL.Text,
  'aiSensitivity' : IDL.Nat,
  'defaultTimeframe' : Timeframe,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'getAnalyses' : IDL.Func([], [IDL.Vec(AnalysisResult)], ['query']),
  'getAnalysisHistory' : IDL.Func([], [IDL.Vec(AnalysisResult)], ['query']),
  'getCriteria' : IDL.Func(
      [],
      [
        IDL.Record({
          'patternRecognitionSensitivity' : IDL.Nat,
          'confidenceBreakpoint' : IDL.Float64,
          'supportResistancePadding' : IDL.Float64,
          'bearishThreshold' : IDL.Float64,
          'trendStrengthMultiplier' : IDL.Float64,
          'bullishThreshold' : IDL.Float64,
        }),
      ],
      ['query'],
    ),
  'getGeminiApiKey' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getSettings' : IDL.Func([], [UserSettings], ['query']),
  'getTopResistanceLevels' : IDL.Func(
      [],
      [IDL.Vec(ResistanceLevel)],
      ['query'],
    ),
  'setGeminiApiKey' : IDL.Func([IDL.Text], [], []),
  'storeExternalAnalysis' : IDL.Func([AnalysisResult], [], []),
  'updateSettings' : IDL.Func([UserSettings], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const AnalysisDirection = IDL.Variant({
    'bullish' : IDL.Null,
    'sideways' : IDL.Null,
    'bearish' : IDL.Null,
  });
  const CandlestickPattern = IDL.Variant({
    'shootingStar' : IDL.Null,
    'doji' : IDL.Null,
    'none' : IDL.Null,
    'hammer' : IDL.Null,
    'engulfing' : IDL.Null,
  });
  const ResistanceLevel = IDL.Record({
    'strength' : IDL.Nat,
    'price' : IDL.Float64,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const AnalysisResult = IDL.Record({
    'direction' : AnalysisDirection,
    'trendStrength' : IDL.Nat,
    'candlestickPatterns' : IDL.Vec(CandlestickPattern),
    'breakouts' : IDL.Bool,
    'resistanceLevels' : IDL.Vec(ResistanceLevel),
    'timestamp' : IDL.Int,
    'confidencePercentage' : IDL.Nat,
    'image' : ExternalBlob,
    'pullbacks' : IDL.Bool,
  });
  const Timeframe = IDL.Variant({
    'M1' : IDL.Null,
    'M5' : IDL.Null,
    'M10' : IDL.Null,
  });
  const UserSettings = IDL.Record({
    'theme' : IDL.Text,
    'signalNotifications' : IDL.Bool,
    'language' : IDL.Text,
    'aiSensitivity' : IDL.Nat,
    'defaultTimeframe' : Timeframe,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'getAnalyses' : IDL.Func([], [IDL.Vec(AnalysisResult)], ['query']),
    'getAnalysisHistory' : IDL.Func([], [IDL.Vec(AnalysisResult)], ['query']),
    'getCriteria' : IDL.Func(
        [],
        [
          IDL.Record({
            'patternRecognitionSensitivity' : IDL.Nat,
            'confidenceBreakpoint' : IDL.Float64,
            'supportResistancePadding' : IDL.Float64,
            'bearishThreshold' : IDL.Float64,
            'trendStrengthMultiplier' : IDL.Float64,
            'bullishThreshold' : IDL.Float64,
          }),
        ],
        ['query'],
      ),
    'getGeminiApiKey' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getSettings' : IDL.Func([], [UserSettings], ['query']),
    'getTopResistanceLevels' : IDL.Func(
        [],
        [IDL.Vec(ResistanceLevel)],
        ['query'],
      ),
    'setGeminiApiKey' : IDL.Func([IDL.Text], [], []),
    'storeExternalAnalysis' : IDL.Func([AnalysisResult], [], []),
    'updateSettings' : IDL.Func([UserSettings], [], []),
  });
};

export const init = ({ IDL }) => { return []; };