/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AnalysisDirection = { 'bullish' : null } |
  { 'sideways' : null } |
  { 'bearish' : null };
export interface AnalysisResult {
  'direction' : AnalysisDirection,
  'trendStrength' : bigint,
  'candlestickPatterns' : Array<CandlestickPattern>,
  'breakouts' : boolean,
  'resistanceLevels' : Array<ResistanceLevel>,
  'timestamp' : bigint,
  'confidencePercentage' : bigint,
  'image' : ExternalBlob,
  'pullbacks' : boolean,
}
export type CandlestickPattern = { 'shootingStar' : null } |
  { 'doji' : null } |
  { 'none' : null } |
  { 'hammer' : null } |
  { 'engulfing' : null };
export type ExternalBlob = Uint8Array;
export interface ResistanceLevel { 'strength' : bigint, 'price' : number }
export type Timeframe = { 'M1' : null } |
  { 'M5' : null } |
  { 'M10' : null };
export interface UserSettings {
  'theme' : string,
  'signalNotifications' : boolean,
  'language' : string,
  'aiSensitivity' : bigint,
  'defaultTimeframe' : Timeframe,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addAnalysis' : ActorMethod<[AnalysisResult], undefined>,
  'getAnalyses' : ActorMethod<[], Array<AnalysisResult>>,
  'getAnalysisHistory' : ActorMethod<[], Array<AnalysisResult>>,
  'getCriteria' : ActorMethod<
    [],
    {
      'patternRecognitionSensitivity' : bigint,
      'confidenceBreakpoint' : number,
      'supportResistancePadding' : number,
      'bearishThreshold' : number,
      'trendStrengthMultiplier' : number,
      'bullishThreshold' : number,
    }
  >,
  'getSettings' : ActorMethod<[], UserSettings>,
  'getTopResistanceLevels' : ActorMethod<[], Array<ResistanceLevel>>,
  'updateSettings' : ActorMethod<[UserSettings], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];