/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ResistanceLevel {
    strength: bigint;
    price: number;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface UserSettings {
    theme: string;
    signalNotifications: boolean;
    language: string;
    aiSensitivity: bigint;
    defaultTimeframe: Timeframe;
    dailyOperationLimit: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface AnalysisResult {
    direction: AnalysisDirection;
    stopExemplo?: number;
    trendStrength: bigint;
    candlestickPatterns: Array<CandlestickPattern>;
    acaoSugerida?: string;
    breakouts: boolean;
    resistanceLevels: Array<ResistanceLevel>;
    probabilidadeBaixa?: number;
    entradaExemplo?: number;
    alvoExemplo?: number;
    probabilidadeAlta?: number;
    timestamp: bigint;
    confidencePercentage: bigint;
    image: ExternalBlob;
    operationFollowed?: boolean;
    pullbacks: boolean;
}
export interface UserProfile {
    name: string;
    email?: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum AnalysisDirection {
    bullish = "bullish",
    sideways = "sideways",
    bearish = "bearish"
}
export enum CandlestickPattern {
    shootingStar = "shootingStar",
    doji = "doji",
    none = "none",
    hammer = "hammer",
    engulfing = "engulfing"
}
export enum Timeframe {
    M1 = "M1",
    M5 = "M5",
    M10 = "M10"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getAnalyses(): Promise<Array<AnalysisResult>>;
    getAnalysisHistory(): Promise<Array<AnalysisResult>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCriteria(): Promise<{
        patternRecognitionSensitivity: bigint;
        confidenceBreakpoint: number;
        supportResistancePadding: number;
        bearishThreshold: number;
        trendStrengthMultiplier: number;
        bullishThreshold: number;
    }>;
    getDailyOperationProgress(userId: Principal): Promise<{
        dailyLimit: bigint;
        completedOperations: bigint;
    }>;
    getSettings(): Promise<UserSettings>;
    getTopResistanceLevels(): Promise<Array<ResistanceLevel>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setDailyOperationLimit(limit: bigint): Promise<string>;
    storeExternalAnalysis(result: AnalysisResult): Promise<void>;
    updateSettings(newSettings: UserSettings): Promise<string>;
}
import type { AnalysisDirection as _AnalysisDirection, AnalysisResult as _AnalysisResult, CandlestickPattern as _CandlestickPattern, ExternalBlob as _ExternalBlob, ResistanceLevel as _ResistanceLevel, Timeframe as _Timeframe, UserProfile as _UserProfile, UserRole as _UserRole, UserSettings as _UserSettings, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAnalyses(): Promise<Array<AnalysisResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalyses();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalyses();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAnalysisHistory(): Promise<Array<AnalysisResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalysisHistory();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalysisHistory();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCriteria(): Promise<{
        patternRecognitionSensitivity: bigint;
        confidenceBreakpoint: number;
        supportResistancePadding: number;
        bearishThreshold: number;
        trendStrengthMultiplier: number;
        bullishThreshold: number;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getCriteria();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCriteria();
            return result;
        }
    }
    async getDailyOperationProgress(arg0: Principal): Promise<{
        dailyLimit: bigint;
        completedOperations: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyOperationProgress(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyOperationProgress(arg0);
            return result;
        }
    }
    async getSettings(): Promise<UserSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getSettings();
                return from_candid_UserSettings_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSettings();
            return from_candid_UserSettings_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTopResistanceLevels(): Promise<Array<ResistanceLevel>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopResistanceLevels();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopResistanceLevels();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n30(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n30(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setDailyOperationLimit(arg0: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.setDailyOperationLimit(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setDailyOperationLimit(arg0);
            return result;
        }
    }
    async storeExternalAnalysis(arg0: AnalysisResult): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.storeExternalAnalysis(await to_candid_AnalysisResult_n32(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storeExternalAnalysis(await to_candid_AnalysisResult_n32(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateSettings(arg0: UserSettings): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSettings(to_candid_UserSettings_n40(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSettings(to_candid_UserSettings_n40(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_AnalysisDirection_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnalysisDirection): AnalysisDirection {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
async function from_candid_AnalysisResult_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnalysisResult): Promise<AnalysisResult> {
    return await from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_CandlestickPattern_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CandlestickPattern): CandlestickPattern {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_Timeframe_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Timeframe): Timeframe {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_UserSettings_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserSettings): UserSettings {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    direction: _AnalysisDirection;
    stopExemplo: [] | [number];
    trendStrength: bigint;
    candlestickPatterns: Array<_CandlestickPattern>;
    acaoSugerida: [] | [string];
    breakouts: boolean;
    resistanceLevels: Array<_ResistanceLevel>;
    probabilidadeBaixa: [] | [number];
    entradaExemplo: [] | [number];
    alvoExemplo: [] | [number];
    probabilidadeAlta: [] | [number];
    timestamp: bigint;
    confidencePercentage: bigint;
    image: _ExternalBlob;
    operationFollowed: [] | [boolean];
    pullbacks: boolean;
}): Promise<{
    direction: AnalysisDirection;
    stopExemplo?: number;
    trendStrength: bigint;
    candlestickPatterns: Array<CandlestickPattern>;
    acaoSugerida?: string;
    breakouts: boolean;
    resistanceLevels: Array<ResistanceLevel>;
    probabilidadeBaixa?: number;
    entradaExemplo?: number;
    alvoExemplo?: number;
    probabilidadeAlta?: number;
    timestamp: bigint;
    confidencePercentage: bigint;
    image: ExternalBlob;
    operationFollowed?: boolean;
    pullbacks: boolean;
}> {
    return {
        direction: from_candid_AnalysisDirection_n13(_uploadFile, _downloadFile, value.direction),
        stopExemplo: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.stopExemplo)),
        trendStrength: value.trendStrength,
        candlestickPatterns: from_candid_vec_n16(_uploadFile, _downloadFile, value.candlestickPatterns),
        acaoSugerida: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.acaoSugerida)),
        breakouts: value.breakouts,
        resistanceLevels: value.resistanceLevels,
        probabilidadeBaixa: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.probabilidadeBaixa)),
        entradaExemplo: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.entradaExemplo)),
        alvoExemplo: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.alvoExemplo)),
        probabilidadeAlta: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.probabilidadeAlta)),
        timestamp: value.timestamp,
        confidencePercentage: value.confidencePercentage,
        image: await from_candid_ExternalBlob_n20(_uploadFile, _downloadFile, value.image),
        operationFollowed: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.operationFollowed)),
        pullbacks: value.pullbacks
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: [] | [string];
}): {
    name: string;
    email?: string;
} {
    return {
        name: value.name,
        email: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.email))
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    theme: string;
    signalNotifications: boolean;
    language: string;
    aiSensitivity: bigint;
    defaultTimeframe: _Timeframe;
    dailyOperationLimit: bigint;
}): {
    theme: string;
    signalNotifications: boolean;
    language: string;
    aiSensitivity: bigint;
    defaultTimeframe: Timeframe;
    dailyOperationLimit: bigint;
} {
    return {
        theme: value.theme,
        signalNotifications: value.signalNotifications,
        language: value.language,
        aiSensitivity: value.aiSensitivity,
        defaultTimeframe: from_candid_Timeframe_n28(_uploadFile, _downloadFile, value.defaultTimeframe),
        dailyOperationLimit: value.dailyOperationLimit
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bullish: null;
} | {
    sideways: null;
} | {
    bearish: null;
}): AnalysisDirection {
    return "bullish" in value ? AnalysisDirection.bullish : "sideways" in value ? AnalysisDirection.sideways : "bearish" in value ? AnalysisDirection.bearish : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    shootingStar: null;
} | {
    doji: null;
} | {
    none: null;
} | {
    hammer: null;
} | {
    engulfing: null;
}): CandlestickPattern {
    return "shootingStar" in value ? CandlestickPattern.shootingStar : "doji" in value ? CandlestickPattern.doji : "none" in value ? CandlestickPattern.none : "hammer" in value ? CandlestickPattern.hammer : "engulfing" in value ? CandlestickPattern.engulfing : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    M1: null;
} | {
    M5: null;
} | {
    M10: null;
}): Timeframe {
    return "M1" in value ? Timeframe.M1 : "M5" in value ? Timeframe.M5 : "M10" in value ? Timeframe.M10 : value;
}
async function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AnalysisResult>): Promise<Array<AnalysisResult>> {
    return await Promise.all(value.map(async (x)=>await from_candid_AnalysisResult_n11(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CandlestickPattern>): Array<CandlestickPattern> {
    return value.map((x)=>from_candid_CandlestickPattern_n17(_uploadFile, _downloadFile, x));
}
function to_candid_AnalysisDirection_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AnalysisDirection): _AnalysisDirection {
    return to_candid_variant_n35(_uploadFile, _downloadFile, value);
}
async function to_candid_AnalysisResult_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AnalysisResult): Promise<_AnalysisResult> {
    return await to_candid_record_n33(_uploadFile, _downloadFile, value);
}
function to_candid_CandlestickPattern_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CandlestickPattern): _CandlestickPattern {
    return to_candid_variant_n38(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_Timeframe_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Timeframe): _Timeframe {
    return to_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n31(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_UserSettings_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserSettings): _UserSettings {
    return to_candid_record_n41(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email?: string;
}): {
    name: string;
    email: [] | [string];
} {
    return {
        name: value.name,
        email: value.email ? candid_some(value.email) : candid_none()
    };
}
async function to_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    direction: AnalysisDirection;
    stopExemplo?: number;
    trendStrength: bigint;
    candlestickPatterns: Array<CandlestickPattern>;
    acaoSugerida?: string;
    breakouts: boolean;
    resistanceLevels: Array<ResistanceLevel>;
    probabilidadeBaixa?: number;
    entradaExemplo?: number;
    alvoExemplo?: number;
    probabilidadeAlta?: number;
    timestamp: bigint;
    confidencePercentage: bigint;
    image: ExternalBlob;
    operationFollowed?: boolean;
    pullbacks: boolean;
}): Promise<{
    direction: _AnalysisDirection;
    stopExemplo: [] | [number];
    trendStrength: bigint;
    candlestickPatterns: Array<_CandlestickPattern>;
    acaoSugerida: [] | [string];
    breakouts: boolean;
    resistanceLevels: Array<_ResistanceLevel>;
    probabilidadeBaixa: [] | [number];
    entradaExemplo: [] | [number];
    alvoExemplo: [] | [number];
    probabilidadeAlta: [] | [number];
    timestamp: bigint;
    confidencePercentage: bigint;
    image: _ExternalBlob;
    operationFollowed: [] | [boolean];
    pullbacks: boolean;
}> {
    return {
        direction: to_candid_AnalysisDirection_n34(_uploadFile, _downloadFile, value.direction),
        stopExemplo: value.stopExemplo ? candid_some(value.stopExemplo) : candid_none(),
        trendStrength: value.trendStrength,
        candlestickPatterns: to_candid_vec_n36(_uploadFile, _downloadFile, value.candlestickPatterns),
        acaoSugerida: value.acaoSugerida ? candid_some(value.acaoSugerida) : candid_none(),
        breakouts: value.breakouts,
        resistanceLevels: value.resistanceLevels,
        probabilidadeBaixa: value.probabilidadeBaixa ? candid_some(value.probabilidadeBaixa) : candid_none(),
        entradaExemplo: value.entradaExemplo ? candid_some(value.entradaExemplo) : candid_none(),
        alvoExemplo: value.alvoExemplo ? candid_some(value.alvoExemplo) : candid_none(),
        probabilidadeAlta: value.probabilidadeAlta ? candid_some(value.probabilidadeAlta) : candid_none(),
        timestamp: value.timestamp,
        confidencePercentage: value.confidencePercentage,
        image: await to_candid_ExternalBlob_n39(_uploadFile, _downloadFile, value.image),
        operationFollowed: value.operationFollowed ? candid_some(value.operationFollowed) : candid_none(),
        pullbacks: value.pullbacks
    };
}
function to_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    theme: string;
    signalNotifications: boolean;
    language: string;
    aiSensitivity: bigint;
    defaultTimeframe: Timeframe;
    dailyOperationLimit: bigint;
}): {
    theme: string;
    signalNotifications: boolean;
    language: string;
    aiSensitivity: bigint;
    defaultTimeframe: _Timeframe;
    dailyOperationLimit: bigint;
} {
    return {
        theme: value.theme,
        signalNotifications: value.signalNotifications,
        language: value.language,
        aiSensitivity: value.aiSensitivity,
        defaultTimeframe: to_candid_Timeframe_n42(_uploadFile, _downloadFile, value.defaultTimeframe),
        dailyOperationLimit: value.dailyOperationLimit
    };
}
function to_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AnalysisDirection): {
    bullish: null;
} | {
    sideways: null;
} | {
    bearish: null;
} {
    return value == AnalysisDirection.bullish ? {
        bullish: null
    } : value == AnalysisDirection.sideways ? {
        sideways: null
    } : value == AnalysisDirection.bearish ? {
        bearish: null
    } : value;
}
function to_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CandlestickPattern): {
    shootingStar: null;
} | {
    doji: null;
} | {
    none: null;
} | {
    hammer: null;
} | {
    engulfing: null;
} {
    return value == CandlestickPattern.shootingStar ? {
        shootingStar: null
    } : value == CandlestickPattern.doji ? {
        doji: null
    } : value == CandlestickPattern.none ? {
        none: null
    } : value == CandlestickPattern.hammer ? {
        hammer: null
    } : value == CandlestickPattern.engulfing ? {
        engulfing: null
    } : value;
}
function to_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Timeframe): {
    M1: null;
} | {
    M5: null;
} | {
    M10: null;
} {
    return value == Timeframe.M1 ? {
        M1: null
    } : value == Timeframe.M5 ? {
        M5: null
    } : value == Timeframe.M10 ? {
        M10: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<CandlestickPattern>): Array<_CandlestickPattern> {
    return value.map((x)=>to_candid_CandlestickPattern_n37(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
